---
title: "CFA - Filene"
author: "Rachael Pyram"
date: "2023-09-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading in data
```{r}
#reading in data
data <- read.csv("C:/Users/racha/Desktop/2021-Data.csv", header = TRUE)
 
library(dplyr)
#only looking pre-2021 (pre-coded in dataset already)
pract <- data %>% select('CU_Name','DEI_Definition_Pre2021' : 'Strategy_Low_High')

#removing #NULL! responses and replacing with NA's
pract = replace (pract, pract == "#NULL!", NA)

#changing from class = character to class = numeric
pract[, -1] = 
pract[, -1] = sapply(pract[, -1], as.numeric)
pract = as.data.frame(pract) #returning to data frame format
pract = na.omit(pract)

```



## Correlation matrix
```{r}
library(psych)

#as data is dichotomous, need to use tetrachoric corr
tcorr = tetrachoric(pract[,-1], y = NULL, correct = TRUE, smooth = TRUE, global = TRUE, weight = NULL, na.rm = TRUE, delete = TRUE)

```




## Leslie CFA
```{r}
library(lavaan)

#creating three factor model; f1 = accountability, f2 = resource, f3 = nondiscrimination
leslie = 'f1 =~ DEI_StrategicPlan_Pre2021	+ BusinessPlan_Alignment_Pre2021 + Perf_Eval_Pre2021 + Manager_Comp_Pre2021 + Goal_Opportunity_Pre2021 + Goal_Hiring_Pre2021 + Goal_Retention_Pre2021 + Goal_EquityPractices_Pre2021 + Goal_FairTreatment_Pre2021 + Goal_EngageTalent_Pre2021 + Goal_Inclusion_Pre2021 + Track_Opportunity_Pre2021 + Track_Hiring_Pre2021 + Track_Retention_Pre2021 + Track_EquityPractices_Pre2021 + Track_FairTreatment_Pre2021 + Track_EngageTalent_Pre2021 + Track_Inclusion_Pre2021 + CDO_Pre2021 + Diversity_Committee_Pre2021
f2 =~ DEI_Definition_Pre2021 + DEI_Statement_Pre2021 + Diversity_Website_Pre2021 + Inclusive_Recruit_Language_Pre2021 + Recruit_Events_Pre2021 + Recruit_Ads_Pre2021 + HBCU_Partnerships_Pre2021 + Leader_IDentification_Pre2021 + Leader_Development_Pre2021 + Mentorship_Pre2021 + Affinity_Groups_Pre2021 + Wirtten_Policy_Supplier_Pre2021 + Outreach_Minority_Business__Pre2021 + Registration_Supplier__Pre2021
f3 =~ Structured_Interviews_Pre2021 + Diverse_Interview_Panels_Pre2021 + Interview_Training_Pre2021 + Oboarding_Pre2021 + DEI_Training_Pre2021'

#running the CFA and obtaining fit indices
cfa_leslie = cfa(leslie, data = pract[,-1], std.lv = TRUE)
summary(cfa_leslie, fit.measures = TRUE)

#plotting the model
library(semPlot)
semPaths(cfa_leslie, residuals = FALSE, "std", layout = "circle2", edge.label.cex = 1.1, sizeMan = 5, sizeLat = 4.5, label.cex = 1.1)

```


## Exporting tetra corr matrix
```{r}

tc_matrix = tcorr$rho
write.csv(tc_matrix, file = "C:/Users/racha/Desktop/tcorr_matrix.csv")


```


